Cherry-picked from merged commits in branch RELEASE_12_1 up to 2014-2-17
988 - HRM

added missing audit log statements for sign off/revoke sign off

3074 demographic export doesn't handle HRM sign-off properly

988 - HRM code fix

ID: #3011 Schedule Screen not refreshing after doing a billing

https://sourceforge.net/p/oscarmcmaster/bugs/3011/

988 - HRM

added some additional audit logging functionality

3071 - Fixed docs handling to work with the abnormal flag

https://sourceforge.net/p/oscarmcmaster/bugs/3071/

Three small icons for this generation of interface for MyOSCAR clinic
component integration or other e-uses

Change-Id: Id138888ff94da322c284ebdde6a41cd66cd9b8e4

ID: #3045, #3069 Manage Contacts, Updated Personal Contact is deleted
Manage Contacts, last submitted record is duplicated on page reload

https://sourceforge.net/p/oscarmcmaster/bugs/3045/
https://sourceforge.net/p/oscarmcmaster/bugs/3069/

Change-Id: Ia7a3c011fa3f8c145e6532b9458c1bf08ec79016

ID: #3006, #3007 OSCAR Rx: Pick up date and time are missing and saved values display as NULL  Life Stage data is missing on Add Allergy Reaction page

https://sourceforge.net/p/oscarmcmaster/bugs/3006/
https://sourceforge.net/p/oscarmcmaster/bugs/3007/

Change-Id: I5e946f954e397458c7c61764b271a691e89d2c79

2811 - Implemented a util class to add demographics, providers and lab & docs to
the inbox for stress testing

https://sourceforge.net/p/oscarmcmaster/bugs/2811/

Change-Id: Idf4acaa0baacf01cf1e03c9a7a1cc0305ddde0a4

3106 HRM class mappings (under admin) are looking at the wrong columns

978 add skeleton measurement web service to support upcoming commit

988 - HRM

fixes to this sign-off business. turns out I didn't need to add
this column (requirements from original design would have been helpful).

patient eChart

Change-Id: Ifc6dd58f6b8d398fe1318e0654ebd85435122200

ID: #3075 Demographic Search returns no result if search query contains spaces

https://sourceforge.net/p/oscarmcmaster/bugs/3075/

ID #3118 Removed restriction to schema named `oscar`, and corrected the
table reference to fix
ERROR [errorpage_jsp:72] Errororg.apache.jasper.
JasperException: javax.servlet.ServletException: java.sql.SQLException:
Base table or view not found

Change-Id: Ie9b152cd48bbb51182aca24b36626f690a57bc96